//! Compile a contract model into Postgres's own enforcement: a `CREATE TABLE`
//! whose column types, `NOT NULL`, `CHECK` and `UNIQUE` constraints reject
//! the rows `covenant check` reports — or a refusal naming each rule that has
//! no exact equivalent.
//!
//! **The claim, precisely.** Insert rows into the table one at a time, with
//! values already of the column types: a row is rejected exactly when the
//! engines report it, given the rows the table holds. That last clause is the
//! one difference in kind: the table enforces the contract on the rows it
//! keeps, so a row it rejected cannot make a later one a duplicate, where
//! `covenant check` reads a dataset as it is. `tests/postgres_test.rs` holds
//! the claim against a real Postgres, on the ODCS conformance vectors and on
//! edge values the engines decide.
//!
//! How a value becomes a `bigint`, `date` or `timestamptz` is the loader's
//! business — a CSV `COPY` parses the text `5` into a bigint that Covenant's
//! JSON check would reject as a string — so the constraints start where the
//! Arrow engine does, from typed values. A `uuid` stays text with a shape
//! check, because Covenant's uuid is a text shape compared as text.

use std::fmt::Write as _;

use serde_json::Value;

use crate::compile::{shape, CompiledContract};
use crate::error::{CovenantError, Result};
use crate::spec::{Contract, Field, FieldType, StringFormat, UnenforcedRule};

/// Postgres truncates identifiers longer than this many bytes.
const MAX_IDENT: usize = 63;
/// The largest repetition count Postgres regular expressions accept.
const MAX_REPEAT: u32 = 255;

/// A contract model as Postgres DDL, and the rules left out of it.
#[derive(Debug, Clone)]
pub struct Export {
    /// The SQL: an encoding guard, the `CREATE TABLE`, and a table comment.
    pub sql: String,
    /// The contract rules the table does not enforce: the upstream ones
    /// passed in, then those with no exact Postgres equivalent. Empty unless
    /// the export was allowed to be partial.
    pub unenforced: Vec<UnenforcedRule>,
}

/// What to export, and how much may be left out.
#[derive(Debug, Clone, Default)]
pub struct Options<'a> {
    /// The model to export; the contract's only model when `None`.
    pub model: Option<&'a str>,
    /// The table's name, optionally `schema.table`; the model's name when
    /// `None`.
    pub table: Option<&'a str>,
    /// Export everything else when some rules have no exact equivalent,
    /// listing them in the SQL, instead of refusing.
    pub allow_unenforced: bool,
    /// Rules already left out before the export — an ODCS reader's — to
    /// list with the dialect's own.
    pub upstream: &'a [UnenforcedRule],
}

/// Export one model as a Postgres table. Refuses, naming every rule, when a
/// rule has no exact equivalent and the options do not allow a partial
/// export.
pub fn export(contract: &Contract, opts: &Options<'_>) -> Result<Export> {
    let compiled = CompiledContract::compile(contract)?;
    let name = compiled.resolve_model(opts.model)?.name.clone();
    let fields = &contract.models[&name].fields;
    let table = match opts.table {
        Some(t) => QualifiedName::parse(t)?,
        None => QualifiedName::bare(&name)?,
    };

    let mut cx = Cx::default();
    let mut columns = Vec::new();
    for (field_name, field) in fields {
        ident(field_name)?;
        columns.push(column(field_name, field, &name, &mut cx));
    }

    if !cx.unenforced.is_empty() && !opts.allow_unenforced {
        return Err(CovenantError::DialectUnenforced {
            dialect: "Postgres".into(),
            count: cx.unenforced.len(),
            details: crate::spec::render_unenforced(&cx.unenforced),
        });
    }
    let mut unenforced = opts.upstream.to_vec();
    unenforced.append(&mut cx.unenforced);

    let mut sql = String::new();
    let _ = writeln!(
        sql,
        "-- Covenant contract {} v{}, model {}, as a Postgres table.",
        contract.id, contract.version, name
    );
    sql.push_str(
        "-- Generated by `covenant export postgres`: regenerate it rather than edit it.\n\
         -- Each constraint is one contract rule, named <column>.<rule>; a row this table\n\
         -- rejects is a row `covenant check` reports. The constraints start from values\n\
         -- of the column types: how text becomes a bigint, date or timestamptz is the\n\
         -- loader's business.\n",
    );
    if contract.policy.max_violations > 0 {
        let _ = writeln!(
            sql,
            "-- The contract tolerates {} violating rows (policy.max_violations); a table\n\
             -- has no such budget and rejects every one.",
            contract.policy.max_violations
        );
    }
    if !unenforced.is_empty() {
        sql.push_str("-- PARTIAL: this table does not enforce these contract rules:\n");
        for r in &unenforced {
            let _ = writeln!(sql, "--   {} ({}): {}", r.path, r.rule, r.reason);
        }
    }
    sql.push_str(
        "\nDO $covenant$\nBEGIN\n  IF current_setting('server_encoding') <> 'UTF8' THEN\n    \
         RAISE EXCEPTION 'this table needs a UTF8 database: its lengths and patterns count characters';\n  \
         END IF;\n  IF current_setting('standard_conforming_strings') <> 'on' THEN\n    \
         RAISE EXCEPTION 'this script needs standard_conforming_strings = on: its patterns hold backslashes';\n  \
         END IF;\nEND\n$covenant$;\n\n",
    );

    let _ = writeln!(sql, "CREATE TABLE {} (", table.sql());
    let mut lines = Vec::new();
    for c in &columns {
        lines.push(format!(
            "  {} {}{}",
            quote_ident(&c.name),
            c.sql_type,
            if c.not_null { " NOT NULL" } else { "" }
        ));
    }
    let mut names = std::collections::HashSet::new();
    for c in &columns {
        for (rule, expr) in &c.checks {
            let constraint = constraint_name(&format!("{}.{rule}", c.name));
            if !names.insert(constraint.clone()) {
                return Err(dialect_error(format!(
                    "two constraints would both be named {constraint:?}"
                )));
            }
            lines.push(format!(
                "  CONSTRAINT {} CHECK ({expr})",
                quote_ident(&constraint)
            ));
        }
    }
    for c in columns.iter().filter(|c| c.unique) {
        // A UNIQUE constraint's index is named after it, and index names are
        // unique per schema, so this one carries the table's name too.
        let constraint = constraint_name(&format!("{}.{}.unique", table.name, c.name));
        if !names.insert(constraint.clone()) {
            return Err(dialect_error(format!(
                "two constraints would both be named {constraint:?}"
            )));
        }
        lines.push(format!(
            "  CONSTRAINT {} UNIQUE ({})",
            quote_ident(&constraint),
            quote_ident(&c.name)
        ));
    }
    sql.push_str(&lines.join(",\n"));
    sql.push_str("\n);\n");
    let _ = writeln!(
        sql,
        "COMMENT ON TABLE {} IS {};",
        table.sql(),
        quote_str(&format!(
            "Covenant contract {} v{}, model {}",
            contract.id, contract.version, name
        ))
    );

    Ok(Export { sql, unenforced })
}

#[derive(Default)]
struct Cx {
    unenforced: Vec<UnenforcedRule>,
}

impl Cx {
    fn refuse(&mut self, model: &str, field: &str, rule: &str, reason: impl Into<String>) {
        self.unenforced.push(UnenforcedRule {
            path: format!("models.{model}.fields.{field}"),
            rule: rule.to_string(),
            reason: reason.into(),
        });
    }
}

struct Column {
    name: String,
    sql_type: &'static str,
    not_null: bool,
    /// (rule, boolean expression), in the order the row engine checks them.
    checks: Vec<(&'static str, String)>,
    unique: bool,
}

fn column(name: &str, field: &Field, model: &str, cx: &mut Cx) -> Column {
    let col = quote_ident(name);
    let mut checks: Vec<(&'static str, String)> = Vec::new();
    let sql_type = match field.ty {
        FieldType::String => "text",
        FieldType::Integer => "bigint",
        FieldType::Float => "double precision",
        FieldType::Boolean => "boolean",
        FieldType::Date => "date",
        FieldType::Timestamp => "timestamptz",
        FieldType::Uuid => {
            checks.push((
                "uuid",
                format!(
                    "({col} COLLATE \"C\") ~ '^[0-9A-Fa-f]{{8}}-[0-9A-Fa-f]{{4}}-[0-9A-Fa-f]{{4}}-[0-9A-Fa-f]{{4}}-[0-9A-Fa-f]{{12}}$'"
                ),
            ));
            "text"
        }
    };

    // The rules each type's check applies (engine::row::check_value), and
    // only those: a rule the engines ignore for this type is not exported.
    match field.ty {
        FieldType::String => {
            if let Some(n) = field.min_length {
                checks.push(("min_length", format!("char_length({col}) >= {n}")));
            }
            if let Some(n) = field.max_length {
                checks.push(("max_length", format!("char_length({col}) <= {n}")));
            }
            if let Some(p) = &field.pattern {
                match pg_regex(p) {
                    Ok(re) => checks.push((
                        "pattern",
                        format!("({col} COLLATE \"C\") ~ {}", quote_str(&re)),
                    )),
                    Err(why) => cx.refuse(model, name, "pattern", why),
                }
            }
            if let Some(fmt) = field.format {
                let ws = white_space(|c| format!("\\u{c:04X}"));
                checks.push((
                    "format",
                    format!(
                        "({col} COLLATE \"C\") ~ {} AND ({col} COLLATE \"C\") !~ {}",
                        quote_str(format_regex(fmt)),
                        quote_str(&format!("[{ws}]"))
                    ),
                ));
            }
            if let Some(values) = &field.allowed {
                checks.push(("allowed", member_of(&col, &text_set(values))));
            }
        }
        FieldType::Integer => {
            // The engines compare integers against the integerized bound
            // (shape::int_below_min); so does this, exactly, in numeric.
            if let Some(min) = field.min {
                checks.push(("min", format!("{col} >= {}", min.ceil() as i128)));
            }
            if let Some(max) = field.max {
                checks.push(("max", format!("{col} <= {}", max.floor() as i128)));
            }
            if let Some(values) = &field.allowed {
                let set: Vec<String> = values
                    .iter()
                    .filter_map(|v| {
                        v.as_i64()
                            .map(|n| n.to_string())
                            .or_else(|| v.as_u64().map(|n| n.to_string()))
                    })
                    .collect();
                checks.push(("allowed", member_of(&col, &set)));
            }
        }
        FieldType::Float => {
            // Covenant passes NaN through both bounds (every comparison with
            // NaN is false); Postgres orders NaN above everything, so NaN
            // passes `>=` there but needs letting through `<=`. A NaN bound
            // passes everything in Covenant, so it is no constraint at all.
            if let Some(min) = field.min.filter(|m| !m.is_nan()) {
                checks.push(("min", format!("{col} >= {}", float8(min))));
            }
            if let Some(max) = field.max.filter(|m| !m.is_nan()) {
                checks.push((
                    "max",
                    format!("({col} <= {} OR {col} = 'NaN'::float8)", float8(max)),
                ));
            }
            if let Some(values) = &field.allowed {
                let set: Vec<String> = values
                    .iter()
                    .filter_map(Value::as_f64)
                    .map(float8)
                    .collect();
                checks.push(("allowed", member_of(&col, &set)));
            }
        }
        FieldType::Boolean => {
            if let Some(values) = &field.allowed {
                let set: Vec<String> = values
                    .iter()
                    .filter_map(Value::as_bool)
                    .map(|b| b.to_string())
                    .collect();
                checks.push(("allowed", member_of(&col, &set)));
            }
        }
        FieldType::Date => {
            // Covenant compares a date's text, but only canonical YYYY-MM-DD
            // text is a date to it, so text and value comparisons agree.
            if let Some(values) = &field.allowed {
                let set: Vec<String> = values
                    .iter()
                    .filter_map(Value::as_str)
                    .filter(|s| shape::is_date(s))
                    .map(|s| format!("{}::date", quote_str(s)))
                    .collect();
                checks.push(("allowed", member_of(&col, &set)));
            }
        }
        FieldType::Uuid => {
            if let Some(values) = &field.allowed {
                checks.push(("allowed", member_of(&col, &text_set(values))));
            }
        }
        FieldType::Timestamp => {
            if field.allowed.is_some() {
                cx.refuse(
                    model,
                    name,
                    "allowed",
                    "Covenant compares a timestamp's text and Postgres its instant: \
                     2026-01-01T00:00:00Z and 2026-01-01T00:00:00+00:00 are two values to one \
                     and one to the other",
                );
            }
        }
    }

    let unique = field.unique
        && if field.ty == FieldType::Timestamp {
            cx.refuse(
                model,
                name,
                "unique",
                "Covenant compares a timestamp's text and Postgres its instant: two renderings \
                 of one instant are distinct to one and duplicates to the other",
            );
            false
        } else {
            true
        };

    Column {
        name: name.to_string(),
        sql_type,
        // `required` alone is structural in a table: every row has every
        // column. A null is refused only when the field is also not nullable
        // — the Arrow engine's reading of a missing value.
        not_null: field.required && !field.nullable,
        checks,
        unique,
    }
}

/// The code points `char::is_whitespace` accepts (Unicode White_Space), as
/// the body of a bracket expression, each written by `code`.
fn white_space(code: impl Fn(u32) -> String) -> String {
    const WHITE_SPACE: [(u32, u32); 10] = [
        (0x09, 0x0D),
        (0x20, 0x20),
        (0x85, 0x85),
        (0xA0, 0xA0),
        (0x1680, 0x1680),
        (0x2000, 0x200A),
        (0x2028, 0x2029),
        (0x202F, 0x202F),
        (0x205F, 0x205F),
        (0x3000, 0x3000),
    ];
    WHITE_SPACE
        .iter()
        .map(|&(lo, hi)| {
            if lo == hi {
                code(lo)
            } else {
                format!("{}-{}", code(lo), code(hi))
            }
        })
        .collect()
}

/// Covenant's email and uri checks (`shape::matches_format`) as regular
/// expressions, for strings with no whitespace in them (the other half of
/// each check). Email: one `@`, something before it, and after it a domain
/// with a dot, neither first nor last. Uri: an RFC 3986 scheme, a colon, and
/// something after it.
fn format_regex(fmt: StringFormat) -> &'static str {
    match fmt {
        StringFormat::Email => r"^[^@]+@[^@.][^@]*\.[^@]*[^@.]$",
        StringFormat::Uri => "^[A-Za-z][A-Za-z0-9+.-]*:.+$",
    }
}

/// The string members of an allowed set as literals. A string holding a NUL
/// is left out: Postgres text cannot hold one, so it matches no stored value.
fn text_set(values: &[Value]) -> Vec<String> {
    values
        .iter()
        .filter_map(Value::as_str)
        .filter(|s| !s.contains('\0'))
        .map(quote_str)
        .collect()
}

/// `col IN (…)`, or no non-null value at all for an empty set. Nulls are
/// the nullability rule's business, never listed (`x IN (…, NULL)` is null,
/// which a CHECK passes).
fn member_of(col: &str, set: &[String]) -> String {
    if set.is_empty() {
        format!("{col} IS NULL")
    } else {
        format!("{col} IN ({})", set.join(", "))
    }
}

/// An f64 as a float8 literal that reads back to the same value.
fn float8(v: f64) -> String {
    let text = if v.is_nan() {
        "NaN".to_string()
    } else if v == f64::INFINITY {
        "Infinity".to_string()
    } else if v == f64::NEG_INFINITY {
        "-Infinity".to_string()
    } else {
        // Display is the shortest text that round-trips.
        v.to_string()
    };
    format!("'{text}'::float8")
}

/// A standard string literal: backslashes are literal, which the script's
/// guard makes sure of (`standard_conforming_strings`).
fn quote_str(s: &str) -> String {
    format!("'{}'", s.replace('\'', "''"))
}

fn quote_ident(s: &str) -> String {
    format!("\"{}\"", s.replace('"', "\"\""))
}

/// A constraint name Postgres keeps as written: at most 63 bytes, with a
/// hash of the full name replacing the tail of a longer one.
fn constraint_name(full: &str) -> String {
    if full.len() <= MAX_IDENT {
        return full.to_string();
    }
    let mut cut = MAX_IDENT - 9;
    while !full.is_char_boundary(cut) {
        cut -= 1;
    }
    let hash = crate::sketch::hash64(full.as_bytes()) as u32;
    format!("{}~{hash:08x}", &full[..cut])
}

fn ident(name: &str) -> Result<()> {
    if name.is_empty() || name.len() > MAX_IDENT || name.contains('\0') {
        return Err(dialect_error(format!(
            "{name:?} cannot be a Postgres identifier (1 to {MAX_IDENT} bytes, no NUL)"
        )));
    }
    Ok(())
}

fn dialect_error(message: String) -> CovenantError {
    CovenantError::Dialect {
        dialect: "Postgres".into(),
        message,
    }
}

/// A table name, optionally schema-qualified.
struct QualifiedName {
    schema: Option<String>,
    name: String,
}

impl QualifiedName {
    fn bare(name: &str) -> Result<Self> {
        ident(name)?;
        Ok(QualifiedName {
            schema: None,
            name: name.to_string(),
        })
    }

    fn parse(text: &str) -> Result<Self> {
        match text.split_once('.') {
            Some((_, name)) if name.contains('.') => Err(dialect_error(format!(
                "{text:?} is not a table name: expected table or schema.table"
            ))),
            Some((schema, name)) => {
                ident(schema)?;
                ident(name)?;
                Ok(QualifiedName {
                    schema: Some(schema.to_string()),
                    name: name.to_string(),
                })
            }
            None => Self::bare(text),
        }
    }

    fn sql(&self) -> String {
        match &self.schema {
            Some(s) => format!("{}.{}", quote_ident(s), quote_ident(&self.name)),
            None => quote_ident(&self.name),
        }
    }
}

/// Translate a pattern (the `regex` crate's syntax, as the engines run it)
/// into a Postgres regular expression that matches exactly the same strings,
/// or say why it cannot. Only a subset both engines read alike is accepted:
/// literals, escaped punctuation, `\n` `\t` `\r`, `.`, anchors, classes of
/// literals and ranges, groups, alternation and repetition. Shorthand classes
/// (`\d`, `\w`, `\s`, `\b`) are refused: they are Unicode-wide in Covenant
/// and locale-dependent in Postgres. `.` becomes `[^\n]`, because Postgres's
/// `.` also matches a newline.
pub fn pg_regex(src: &str) -> std::result::Result<String, String> {
    if src.contains('\0') {
        return Err("Postgres text cannot hold a NUL character".into());
    }
    let chars: Vec<char> = src.chars().collect();
    let mut out = String::with_capacity(src.len() + 8);
    let mut i = 0;
    // Whether the previous token can take a quantifier, and whether it was
    // one (a second quantifier may only be the lazy `?`).
    let mut atom = false;
    let mut quantified = false;
    while i < chars.len() {
        let c = chars[i];
        match c {
            '\\' => {
                let e = *chars
                    .get(i + 1)
                    .ok_or("the pattern ends in a lone backslash")?;
                out.push_str(&escape(e)?);
                i += 2;
                atom = true;
                quantified = false;
            }
            '.' => {
                out.push_str("[^\\n]");
                i += 1;
                atom = true;
                quantified = false;
            }
            '[' => {
                let (class, next) = class(&chars, i)?;
                out.push_str(&class);
                i = next;
                atom = true;
                quantified = false;
            }
            '(' => {
                if chars.get(i + 1) == Some(&'?') {
                    if chars.get(i + 2) != Some(&':') {
                        return Err(
                            "flags and named groups ((?i), (?P<name>…)) are not exported".into(),
                        );
                    }
                    out.push_str("(?:");
                    i += 3;
                } else {
                    out.push('(');
                    i += 1;
                }
                if matches!(chars.get(i), Some(')') | Some('|')) {
                    return Err("an empty group or alternative is not exported".into());
                }
                atom = false;
                quantified = false;
            }
            ')' => {
                out.push(')');
                i += 1;
                atom = true;
                quantified = false;
            }
            '|' => {
                if i == 0 || matches!(chars.get(i + 1), None | Some('|') | Some(')')) {
                    return Err("an empty alternative is not exported".into());
                }
                out.push('|');
                i += 1;
                atom = false;
                quantified = false;
            }
            '^' | '$' => {
                out.push(c);
                i += 1;
                atom = false;
                quantified = false;
            }
            '*' | '+' | '?' => {
                if quantified && c == '?' {
                    out.push('?'); // lazy: the same strings match
                    i += 1;
                    quantified = false;
                    atom = false;
                    continue;
                }
                if !atom {
                    return Err(format!("{c} does not follow something to repeat"));
                }
                out.push(c);
                i += 1;
                atom = false;
                quantified = true;
            }
            '{' => {
                if !atom {
                    return Err("a repetition does not follow something to repeat".into());
                }
                let (rep, next) = repetition(&chars, i)?;
                out.push_str(&rep);
                i = next;
                atom = false;
                quantified = true;
            }
            ']' | '}' => {
                return Err(format!("an unescaped {c} is not exported: write \\{c}"));
            }
            _ => {
                out.push(c);
                i += 1;
                atom = true;
                quantified = false;
            }
        }
    }
    Ok(out)
}

/// An escape outside a class: escaped punctuation is the character itself in
/// both engines, and `\n` `\t` `\r` are the same control characters.
fn escape(e: char) -> std::result::Result<String, String> {
    match e {
        'n' | 't' | 'r' => Ok(format!("\\{e}")),
        // Word boundaries in the regex crate, literals in Postgres.
        '<' | '>' => Err(format!(
            "\\{e} is a word boundary in Covenant and a literal {e} in Postgres"
        )),
        c if c.is_ascii_punctuation() => Ok(format!("\\{c}")),
        'd' | 'D' | 'w' | 'W' | 's' | 'S' | 'b' | 'B' => Err(format!(
            "\\{e} is Unicode-wide in Covenant and locale-dependent in Postgres: \
             spell the characters out, e.g. [0-9] for \\d"
        )),
        other => Err(format!("the escape \\{other} is not exported")),
    }
}

/// A bracketed class starting at `start`, and the index after it. Members
/// are literals, escaped punctuation, `\n` `\t` `\r`, and ranges between
/// them; Rust's nested classes and set operations are refused.
fn class(chars: &[char], start: usize) -> std::result::Result<(String, usize), String> {
    let mut out = String::from("[");
    let mut i = start + 1;
    if chars.get(i) == Some(&'^') {
        out.push('^');
        i += 1;
    }
    if chars.get(i) == Some(&']') {
        return Err("a class starting with ] is not exported: write \\]".into());
    }
    let mut members = 0;
    loop {
        let c = *chars.get(i).ok_or("an unclosed class")?;
        match c {
            ']' => {
                if members == 0 {
                    return Err("an empty class is not exported".into());
                }
                out.push(']');
                return Ok((out, i + 1));
            }
            '[' => return Err("nested classes and [:name:] classes are not exported".into()),
            '\\' => {
                let e = *chars.get(i + 1).ok_or("an unclosed class")?;
                out.push_str(&escape(e)?);
                i += 2;
            }
            '&' | '~' if chars.get(i + 1) == Some(&c) => {
                return Err(format!("the class operation {c}{c} is not exported"));
            }
            '-' if chars.get(i + 1) == Some(&'-') => {
                return Err("the class operation -- is not exported".into());
            }
            _ => {
                out.push(c);
                i += 1;
            }
        }
        members += 1;
    }
}

/// `{n}`, `{n,}` or `{n,m}` at `start`, and the index after it.
fn repetition(chars: &[char], start: usize) -> std::result::Result<(String, usize), String> {
    let close = chars[start..]
        .iter()
        .position(|&c| c == '}')
        .map(|p| start + p)
        .ok_or("an unclosed repetition")?;
    let body: String = chars[start + 1..close].iter().collect();
    let (lo, hi) = match body.split_once(',') {
        Some((lo, hi)) => (lo, Some(hi)),
        None => (body.as_str(), None),
    };
    let number = |s: &str| -> std::result::Result<u32, String> {
        if s.is_empty() || !s.bytes().all(|b| b.is_ascii_digit()) {
            return Err(format!("the repetition {{{body}}} is not exported"));
        }
        let n: u32 = s
            .parse()
            .map_err(|_| format!("the repetition {{{body}}} is too large"))?;
        if n > MAX_REPEAT {
            return Err(format!(
                "Postgres repeats at most {MAX_REPEAT} times, and {{{body}}} asks for more"
            ));
        }
        Ok(n)
    };
    let lo = number(lo)?;
    let rep = match hi {
        None => format!("{{{lo}}}"),
        Some("") => format!("{{{lo},}}"),
        Some(hi) => {
            let hi = number(hi)?;
            format!("{{{lo},{hi}}}")
        }
    };
    Ok((rep, close + 1))
}

#[cfg(test)]
mod tests {
    use super::{format_regex, pg_regex, white_space};
    use crate::compile::shape;
    use crate::spec::StringFormat;

    /// The format regexes accept exactly what the engines' format checks do:
    /// every string of up to five characters over an alphabet of the
    /// characters that matter, the same expressions compiled by the regex
    /// crate. Postgres reading them alike is `tests/postgres_test.rs`'s job.
    #[test]
    fn format_regexes_are_the_engine_checks() {
        let ws =
            regex::Regex::new(&format!("[{}]", white_space(|c| format!("\\x{{{c:X}}}")))).unwrap();
        let alphabet = [
            'a', 'Z', '0', '@', '.', ':', '+', '-', ' ', '\u{a0}', '\u{3000}', 'é',
        ];
        for fmt in [StringFormat::Email, StringFormat::Uri] {
            let re = regex::Regex::new(format_regex(fmt)).unwrap();
            let mut word = Vec::new();
            let mut checked = 0;
            loop {
                let s: String = word.iter().map(|&i| alphabet[i]).collect();
                assert_eq!(
                    re.is_match(&s) && !ws.is_match(&s),
                    shape::matches_format(fmt, &s),
                    "{} {s:?}",
                    fmt.name()
                );
                checked += 1;
                // Next word: count up in base alphabet.len().
                let mut i = 0;
                loop {
                    if i == word.len() {
                        word.push(0);
                        break;
                    }
                    word[i] += 1;
                    if word[i] < alphabet.len() {
                        break;
                    }
                    word[i] = 0;
                    i += 1;
                }
                if word.len() > 5 {
                    break;
                }
            }
            assert!(checked > 250_000, "{checked}");
        }
        // Every code point, where whitespace hides among the others.
        let re = regex::Regex::new(format_regex(StringFormat::Email)).unwrap();
        for c in (0..=0x10FFFFu32).filter_map(char::from_u32) {
            let s = format!("a{c}b@c.d");
            assert_eq!(
                re.is_match(&s) && !ws.is_match(&s),
                shape::matches_format(StringFormat::Email, &s),
                "{c:?}"
            );
        }
    }

    #[test]
    fn patterns_translate_or_are_refused_with_a_reason() {
        for (src, want) in [
            ("^ord_[a-z0-9]{4}$", "^ord_[a-z0-9]{4}$"),
            ("a.b", "a[^\\n]b"),
            ("^(?:ab|c)+?x{2,}y{1,3}$", "^(?:ab|c)+?x{2,}y{1,3}$"),
            (r"\.\$\\\n[\]\-a-]", r"\.\$\\\n[\]\-a-]"),
            ("[^日本]é", "[^日本]é"),
            ("", ""),
        ] {
            assert_eq!(pg_regex(src).as_deref(), Ok(want), "{src}");
        }
        for (src, says) in [
            (r"^\d{5}$", "Unicode-wide"),
            (r"\bword", "Unicode-wide"),
            ("(?i)abc", "flags"),
            ("[[:alpha:]]", "nested classes"),
            ("[a&&b]", "&&"),
            ("a{256}", "at most 255"),
            ("a|", "empty alternative"),
            ("()", "empty group"),
            (r"\x41", "\\x"),
            (r"\<word\>", "word boundary"),
            ("a}", "unescaped }"),
        ] {
            let err = pg_regex(src).unwrap_err();
            assert!(err.contains(says), "{src}: {err}");
        }
    }
}
